"""
Django settings for ai_report project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()



CLICKHOUSE_CONFIG = {
    "host": os.getenv("CH_HOST", "localhost"),
    "port": int(os.getenv("CH_PORT", "9000")),
    "user": os.getenv("CH_USER", "default"),
    "password": os.getenv("CH_PASSWORD", ""),
    "database": os.getenv("CH_DATABASE", "dw"),
    "settings": {
        "use_numpy": True,
        "max_execution_time": 1800,  # เพิ่มเป็น 30 นาที
        "max_memory_usage": 10000000000,  # 10GB memory limit
        "max_threads": 2,  # ลดจำนวน threads เพื่อลดการแย่งทรัพยากร
        "max_insert_block_size": 1000000,  # เพิ่มขนาด block
        "min_insert_block_size_rows": 1000,  # ขนาด block ขั้นต่ำ
        "min_insert_block_size_bytes": 268435456,  # 256MB
    },
    "send_receive_timeout": 1800,  # เพิ่มเป็น 30 นาที
    "sync_request_timeout": 1800,  # เพิ่มเป็น 30 นาที
    "connect_timeout": 60,  # 1 นาทีสำหรับการเชื่อมต่อ
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+c=q3a-)14-qd7j%5v-!o8#9ot0cis_^yia&n@f9#q#f%my@!^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_report.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_report.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB (เพิ่มจาก 25MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB (เพิ่มจาก 25MB)

# เพิ่ม timeout สำหรับ request ที่ใช้เวลานาน
CONN_MAX_AGE = 3600  # 1 hour connection reuse

